apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  PGADMIN_DEFAULT_PASSWORD: psltest